In [5]:
import pandas as pd
from googletrans import Translator
import locale
base= pd.read_csv('train.csv')



# Função para traduzir um texto
def traduzir_texto(texto):
    translator = Translator()
    try:
        return translator.translate(texto, dest='pt').text
    except:
        return texto

# Traduzir os nomes das colunas
base.columns = [traduzir_texto(coluna) for coluna in base.columns]

# Salvar o DataFrame com os novos nomes das colunas
base.to_csv('seuarquivo_traduzido.csv', index=False)

In [30]:
base

,EU IA,Montante do empréstimo,Valor financiado,Valor financiado investidor,Prazo,Lotes inscritos,Taxa de juro,Nota,Sub -grau,Duração do emprego,...,Recuperações,Taxa de recuperação de coleta,Coleção 12 meses Médicos,tipo de aplicação,Na semana passada paga,Contas inadimplentes,Valor total da coleta,Balanço atual total,Limite total de crédito rotativo,Status do empréstimo
0,65087372,10000,32236,12329.36286,59,BAT2522922,11.135007,B,C4,MORTGAGE,...,2.498291,0.793724,0,INDIVIDUAL,49,0,31,311301,6619,0
1,1450153,3609,11940,12191.99692,59,BAT1586599,12.237563,C,D3,RENT,...,2.377215,0.974821,0,INDIVIDUAL,109,0,53,182610,20885,0
2,1969101,28276,9311,21603.22455,59,BAT2136391,12.545884,F,D4,MORTGAGE,...,4.316277,1.020075,0,INDIVIDUAL,66,0,34,89801,26155,0
3,6651430,11170,6954,17877.15585,59,BAT2428731,16.731201,C,C3,MORTGAGE,...,0.107020,0.749971,0,INDIVIDUAL,39,0,40,9189,60214,0
4,14354669,16890,13226,13539.92667,59,BAT5341619,15.008300,C,D4,MORTGAGE,...,1294.818751,0.368953,0,INDIVIDUAL,18,0,430,126029,22579,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67458,16164945,13601,6848,13175.28583,59,BAT3193689,9.408858,C,A4,MORTGAGE,...,564.614852,0.865230,0,INDIVIDUAL,69,0,48,181775,34301,1
67459,35182714,8323,11046,15637.46301,59,BAT1780517,9.972104,C,B3,RENT,...,2.015494,1.403368,0,INDIVIDUAL,14,0,37,22692,8714,0
67460,16435904,15897,32921,12329.45775,59,BAT1761981,19.650943,A,F3,MORTGAGE,...,5.673092,1.607093,0,INDIVIDUAL,137,0,17,176857,42330,0
67461,5300325,16567,4975,21353.68465,59,BAT2333412,13.169095,D,E3,OWN,...,1.157454,0.207608,0,INDIVIDUAL,73,0,61,361339,39075,0
67462,65443173,15353,29875,14207.44860,59,BAT1930365,16.034631,B,D1,MORTGAGE,...,1.856480,0.366386,0,INDIVIDUAL,54,0,47,196960,66060,0

In [32]:
print(base.describe())

              EU IA  Montante do empréstimo  Valor financiado  \
count  6.746300e+04            67463.000000      67463.000000
mean   2.562761e+07            16848.902776      15770.599114
std    2.109155e+07             8367.865726       8150.992662
min    1.297933e+06             1014.000000       1014.000000
25%    6.570288e+06            10012.000000       9266.500000
50%    1.791565e+07            16073.000000      13042.000000
75%    4.271521e+07            22106.000000      21793.000000
max    7.224578e+07            35000.000000      34999.000000

       Valor financiado investidor         Prazo  Taxa de juro  \
count                 67463.000000  67463.000000  67463.000000
mean                  14621.799323     58.173814     11.846258
std                    6785.345170      3.327441      3.718629
min                    1114.590204     36.000000      5.320006
25%                    9831.684984     58.000000      9.297147
50%                   12793.682170     59.000000     11.377696
75%                   17807.594120     59.000000     14.193533
max                   34999.746430     59.000000     27.182348

       Propriedade da casa  Débito à renda  Delinquência - dois anos  \
count         67463.000000    67463.000000              67463.000000
mean          80541.502522       23.299241                  0.327127
std           45029.120366        8.451824                  0.800888
min           14573.537170        0.675299                  0.000000
25%           51689.843335       16.756416                  0.000000
50%           69335.832680       22.656658                  0.000000
75%           94623.322785       30.048400                  0.000000
max          406561.536400       39.629862                  8.000000

       Consultas - seis meses  ...  Taxa de atraso recebida total  \
count            67463.000000  ...                   67463.000000
mean                 0.145754  ...                       1.143969
std                  0.473291  ...                       5.244365
min                  0.000000  ...                       0.000003
25%                  0.000000  ...                       0.021114
50%                  0.000000  ...                       0.043398
75%                  0.000000  ...                       0.071884
max                  5.000000  ...                      42.618882

       Recuperações  Taxa de recuperação de coleta  Coleção 12 meses Médicos  \
count  67463.000000                   67463.000000              67463.000000
mean      59.691578                       1.125141                  0.021301
std      357.026346                       3.489885                  0.144385
min        0.000036                       0.000036                  0.000000
25%        1.629818                       0.476259                  0.000000
50%        3.344524                       0.780141                  0.000000
75%        5.453727                       1.070566                  0.000000
max     4354.467419                     166.833000                  1.000000

       Na semana passada paga  Contas inadimplentes  Valor total da coleta  \
count            67463.000000               67463.0           67463.000000
mean                71.163260                   0.0             146.467990
std                 43.315845                   0.0             744.382233
min                  0.000000                   0.0               1.000000
25%                 35.000000                   0.0              24.000000
50%                 68.000000                   0.0              36.000000
75%                105.000000                   0.0              46.000000
max                161.000000                   0.0           16421.000000

       Balanço atual total  Limite total de crédito rotativo  \
count         6.746300e+04                      67463.000000
mean          1.595739e+05                      23123.005544
std           1.390332e+05                      20916.699999
min           6.170000e+02                       1000.000000
25%           5.037900e+04                       8155.500000
50%           1.183690e+05                      16733.000000
75%           2.283750e+05                      32146.500000
max           1.177412e+06                     201169.000000

       Status do empréstimo
count          67463.000000
mean               0.092510
std                0.289747
min                0.000000
25%                0.000000
50%                0.000000
75%                0.000000
max                1.000000

[8 rows x 26 columns]

In [29]:
base = base.dropna()

In [2]:
import pandas as pd

# Supondo que 'base' seja o seu DataFrame
# Se precisar, substitua 'base' pelo nome do seu DataFrame

# Defina uma função para formatar os valores em reais abreviados
def formatar_em_reais(valor):
    return f'R$ {valor:,.2f}'.replace('.', ',')

# Encontrar o maior valor do empréstimo
maior_valor_emprestimo = base['Montante do empréstimo'].max()

# Encontrar o menor valor do empréstimo
menor_valor_emprestimo = base['Montante do empréstimo'].min()

# Encontrar a média do valor do empréstimo
media_valor_emprestimo = base['Montante do empréstimo'].mean()

# Calcular a soma dos valores do empréstimo
soma_valor_emprestimo = base['Montante do empréstimo'].sum()

# Formatar os resultados em reais abreviados
maior_valor_emprestimo_formatado = formatar_em_reais(maior_valor_emprestimo)
menor_valor_emprestimo_formatado = formatar_em_reais(menor_valor_emprestimo)
media_valor_emprestimo_formatado = formatar_em_reais(media_valor_emprestimo)
soma_valor_emprestimo_formatado = formatar_em_reais(soma_valor_emprestimo)

# Exibir os resultados formatados
print(f"Maior Valor do Empréstimo: {maior_valor_emprestimo_formatado}")
print(f"Menor Valor do Empréstimo: {menor_valor_emprestimo_formatado}")
print(f"Média do Valor do Empréstimo: {media_valor_emprestimo_formatado}")
print(f"Soma do Valor do Empréstimo: {soma_valor_emprestimo_formatado}")

Maior Valor do Empréstimo: R$ 35,000,00
Menor Valor do Empréstimo: R$ 1,014,00
Média do Valor do Empréstimo: R$ 16,848,90
Soma do Valor do Empréstimo: R$ 1,136,677,528,00

In [3]:
maior_prazo = base['Prazo'].max()

# Encontrar o menor valor do empréstimo
menor_prazo = base['Prazo'].min()

# Encontrar a média do valor do empréstimo
media_prazo = base['Prazo'].mean()

print(f"Maior Prazo: {maior_prazo}")
print(f"Menor Prazo: {menor_prazo}")
print(f"Média Prazo: {media_prazo}")

Maior Prazo: 59
Menor Prazo: 36
Média Prazo: 58.17381379422795

In [11]:
base['Taxa de juro'].unique()

array([11.13500686, 12.23756263, 12.54588365, ..., 19.65094342,
       13.16909487, 16.03463076])

In [14]:
base['Lotes inscritos'].unique()

array(['BAT2522922', 'BAT1586599', 'BAT2136391', 'BAT2428731',
       'BAT5341619', 'BAT4694572', 'BAT4808022', 'BAT2558388',
       'BAT2078974', 'BAT2252229', 'BAT2333412', 'BAT5849876',
       'BAT2833642', 'BAT2803411', 'BAT5525466', 'BAT5714674',
       'BAT2003848', 'BAT4722912', 'BAT3873588', 'BAT1780517',
       'BAT4271519', 'BAT5811547', 'BAT1184694', 'BAT4136152',
       'BAT3193689', 'BAT1467036', 'BAT2575549', 'BAT4351734',
       'BAT1104812', 'BAT5924421', 'BAT1930365', 'BAT1766061',
       'BAT5489674', 'BAT3865626', 'BAT5629144', 'BAT5547201',
       'BAT224923', 'BAT3726927', 'BAT3461431', 'BAT1761981',
       'BAT1135695'], dtype=object)

In [20]:
maior_prazo = base['Taxa de juro'].max()

# Encontrar o menor valor do empréstimo
menor_prazo = base['Taxa de juro'].min()

# Encontrar a média do valor do empréstimo
media_prazo = base['Taxa de juro'].mean()

print(f"Maior taxa: {maior_prazo:.0f}%")
print(f"Menor taxa: {menor_prazo:.0f}%")
print(f"Média taxa: {media_prazo:.0f}%")

Maior taxa: 27%
Menor taxa: 5%
Média taxa: 12%

In [8]:
base['Prazo'].unique()

array([59, 36, 58], dtype=int64)

In [22]:
base['Nota'].unique()

array(['B', 'C', 'F', 'A', 'G', 'E', 'D'], dtype=object)

In [25]:
base['Sub -grau'].unique()

array(['C4', 'D3', 'D4', 'C3', 'G5', 'C5', 'A5', 'C2', 'B5', 'B1', 'B4',
       'A4', 'B2', 'D2', 'C1', 'F3', 'D1', 'F2', 'A2', 'A3', 'F1', 'E5',
       'B3', 'F4', 'G1', 'F5', 'E1', 'E2', 'D5', 'G2', 'E4', 'A1', 'G3',
       'E3', 'G4'], dtype=object)

In [28]:
base

,EU IA,Montante do empréstimo,Valor financiado,Valor financiado investidor,Prazo,Lotes inscritos,Taxa de juro,Nota,Sub -grau,Duração do emprego,...,Recuperações,Taxa de recuperação de coleta,Coleção 12 meses Médicos,tipo de aplicação,Na semana passada paga,Contas inadimplentes,Valor total da coleta,Balanço atual total,Limite total de crédito rotativo,Status do empréstimo
0,65087372,10000,32236,12329.36286,59,BAT2522922,11.135007,B,C4,MORTGAGE,...,2.498291,0.793724,0,INDIVIDUAL,49,0,31,311301,6619,0
1,1450153,3609,11940,12191.99692,59,BAT1586599,12.237563,C,D3,RENT,...,2.377215,0.974821,0,INDIVIDUAL,109,0,53,182610,20885,0
2,1969101,28276,9311,21603.22455,59,BAT2136391,12.545884,F,D4,MORTGAGE,...,4.316277,1.020075,0,INDIVIDUAL,66,0,34,89801,26155,0
3,6651430,11170,6954,17877.15585,59,BAT2428731,16.731201,C,C3,MORTGAGE,...,0.107020,0.749971,0,INDIVIDUAL,39,0,40,9189,60214,0
4,14354669,16890,13226,13539.92667,59,BAT5341619,15.008300,C,D4,MORTGAGE,...,1294.818751,0.368953,0,INDIVIDUAL,18,0,430,126029,22579,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67458,16164945,13601,6848,13175.28583,59,BAT3193689,9.408858,C,A4,MORTGAGE,...,564.614852,0.865230,0,INDIVIDUAL,69,0,48,181775,34301,1
67459,35182714,8323,11046,15637.46301,59,BAT1780517,9.972104,C,B3,RENT,...,2.015494,1.403368,0,INDIVIDUAL,14,0,37,22692,8714,0
67460,16435904,15897,32921,12329.45775,59,BAT1761981,19.650943,A,F3,MORTGAGE,...,5.673092,1.607093,0,INDIVIDUAL,137,0,17,176857,42330,0
67461,5300325,16567,4975,21353.68465,59,BAT2333412,13.169095,D,E3,OWN,...,1.157454,0.207608,0,INDIVIDUAL,73,0,61,361339,39075,0
67462,65443173,15353,29875,14207.44860,59,BAT1930365,16.034631,B,D1,MORTGAGE,...,1.856480,0.366386,0,INDIVIDUAL,54,0,47,196960,66060,0

In [26]:
base['Duração do emprego'].unique()

array(['MORTGAGE', 'RENT', 'OWN'], dtype=object)

In [4]:
base.columns.tolist()

['EU IA',
 'Montante do empréstimo',
 'Valor financiado',
 'Valor financiado investidor',
 'Prazo',
 'Lotes inscritos',
 'Taxa de juro',
 'Nota',
 'Sub -grau',
 'Duração do emprego',
 'Propriedade da casa',
 'Status de verificação',
 'Plano de pagamento',
 'Título do empréstimo',
 'Débito à renda',
 'Delinquência - dois anos',
 'Consultas - seis meses',
 'Conta aberta',
 'Registro público',
 'Equilíbrio giratório',
 'Utilitários giratórios',
 'Contas totais',
 'Status inicial da lista',
 'Total recebeu juros',
 'Taxa de atraso recebida total',
 'Recuperações',
 'Taxa de recuperação de coleta',
 'Coleção 12 meses Médicos',
 'tipo de aplicação',
 'Na semana passada paga',
 'Contas inadimplentes',
 'Valor total da coleta',
 'Balanço atual total',
 'Limite total de crédito rotativo',
 'Status do empréstimo']